Resources:
  # Storage
  ## S3 buckets
  RajyamNonProdS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "rajyam-non-prod-s3-bucket"

  ## Dynamo DB
  ChainTableNonProd:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "Chain"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: S
        - AttributeName: "type"
          AttributeType: S
        - AttributeName: "title"
          AttributeType: S
        - AttributeName: "generatedTitle"
          AttributeType: S
        - AttributeName: "createdAt"
          AttributeType: N
        - AttributeName: "updatedAt"
          AttributeType: N
        - AttributeName: "participants"
          AttributeType: L
        - AttributeName: "summary"
          AttributeType: S
        - AttributeName: "messages"
          AttributeType: L
      KeySchema:
        - AttributeName: "id"
          KeyType: HASH
        - AttributeName: "lastActive"
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
  # IAM Policy
  ## Users
  LocalUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "local-user"

  NonProdUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "non-prod-user"

  ## User Groups
  NonProdParameterReaderGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "non-prod-parameter-reader-group"

  NonProdDynamoRWGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "non-prod-dynamo-rw-group"
  ## User - User Group association
  NonProdParameterReaderGroupMembership:
    Type: "AWS::IAM::UserToGroupAddition"
    Properties:
      GroupName:
        Ref: "NonProdParameterReaderGroup"
      Users:
        - Ref: "LocalUser"
        - Ref: "NonProdUser"

  NonProdDynamoRWGroupMembership:
    Type: "AWS::IAM::UserToGroupAddition"
    Properties:
      GroupName:
        Ref: "NonProdDynamoRWGroup"
      Users:
        - Ref: "LocalUser"
        - Ref: "NonProdUser"
  ## Policy
  NonProdParameterStorePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "non-prod-parameter-store-policy"
      Groups:
        - Ref: "NonProdParameterReaderGroup"
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Action:
              - "ssm:GetParameter"
            Resource: "arn:aws:ssm:us-east-2:730335557466:parameter/DISCORD_APP_ID"
          - Effect: "Allow"
            Action:
              - "ssm:GetParameter"
            Resource: "arn:aws:ssm:us-east-2:730335557466:parameter/DISCORD_BOT_V1_TOKEN"
          - Effect: "Allow"
            Action:
              - "ssm:GetParameter"
            Resource: "arn:aws:ssm:us-east-2:730335557466:parameter/LANGCHAIN_API_KEY"
          - Effect: "Allow"
            Action:
              - "ssm:GetParameter"
            Resource: "arn:aws:ssm:us-east-2:730335557466:parameter/OPENAI_API_KEY"
  NonProdDynamoRWPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "non-prod-dynamo-rw-policy"
      Groups:
        - Ref: "NonProdDynamoRWGroup"
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:BatchGetItem"
              - "dynamodb:PutItem"
              - "dynamodb:UpdateItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:BatchWriteItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
            Resource: !GetAtt ChainTableNonProd.Arn
